#!/usr/bin/env bash
# sync-vault.sh — Regenerate the Obsidian human-mirror of the System Packs.
#
# Reads the canonical .claude/systems/{registry.yaml,<domain>.yaml,n8n-fleet.json} and
# (re)writes into the auto-memory vault:
#   _Systems.md                  -> Dataview dashboard of all packs + fleet-by-domain
#   system_<domain>.md           -> one page per authored manifest (skills/workflows/rules/...)
#   n8n_<slug>.md                -> one page per workflow referenced by an authored manifest
#
# Idempotent. Generated files carry a DO-NOT-EDIT banner; edit manifests + re-run instead.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
VAULT="${HOME}/.claude/projects/-Users-makwa-theinnovativenative/memory"

# Prefer the repo venv python (has pyyaml); fall back to system python3.
PY="${REPO_ROOT}/venv/bin/python3"
[ -x "$PY" ] || PY="$(command -v python3)"
[ -n "$PY" ] || { echo "FATAL: python3 not found" >&2; exit 1; }
[ -d "$VAULT" ] || { echo "FATAL: vault not found at $VAULT" >&2; exit 1; }

SYS_DIR="${REPO_ROOT}/.claude/systems" VAULT_DIR="$VAULT" "$PY" - <<'PYEOF'
import os, re, json, glob, yaml

SYS = os.environ["SYS_DIR"]
VAULT = os.environ["VAULT_DIR"]

def slug(s):
    s = s.lower().replace("&", " and ")
    s = re.sub(r"[^a-z0-9]+", "_", s).strip("_")
    s = re.sub(r"_+", "_", s)
    return s

registry = yaml.safe_load(open(os.path.join(SYS, "registry.yaml")))
fleet = json.load(open(os.path.join(SYS, "n8n-fleet.json")))
wf_by_id = {w["id"]: w for w in fleet["workflows"]}
_dpath = os.path.join(SYS, "n8n-detail.json")
detail = json.load(open(_dpath))["detail"] if os.path.exists(_dpath) else {}

BANNER = "> Generated by `scripts/systems/sync-vault.sh` from `.claude/systems/`. Do not hand-edit — edit the manifest and re-run."

written = []

def write(path, text):
    with open(path, "w") as f:
        f.write(text)
    written.append(os.path.basename(path))

# --- per-domain manifests that actually exist (pilot) ---
authored = []
for key, meta in registry["domains"].items():
    mpath = os.path.join(SYS, meta["manifest"])
    if not os.path.exists(mpath):
        continue
    m = yaml.safe_load(open(mpath))
    if not m or "domain" not in m:
        continue
    authored.append(m)

def wikilist(items):
    return "\n".join(f"- [[{x}]]" for x in items) if items else "_none_"

def codelist(items):
    return ", ".join(f"`{x}`" for x in items) if items else "_none_"

for m in authored:
    dom = m["domain"]
    sysname = f"system_{slug(dom)}"
    skills = m.get("skills", {}) or {}
    primary = skills.get("primary", []) or []
    support = skills.get("support", []) or []
    # workflow rows resolved against the fleet
    rows = []
    wf_pages = []
    for wid in m.get("n8n_workflows", []) or []:
        w = wf_by_id.get(wid)
        if not w:
            rows.append(f"| ⚠️ missing | `{wid}` | (not in fleet — re-run build-fleet.sh) |")
            continue
        wslug = f"n8n_{slug(w['name'])}"
        rows.append(f"| {w['status']} | [[{wslug}\\|{w['name']}]] | `{wid}` |")
        wf_pages.append((wslug, w, dom, sysname))
    wf_table = "| Status | Workflow | ID |\n|---|---|---|\n" + ("\n".join(rows) if rows else "| | _none_ | |")

    desc = (m.get("description") or "").strip().replace("\n", " ")
    body = f"""---
name: {sysname}
description: "System Pack: {m['title']} — skills, n8n workflows, brand rules, and mechanical agents /goal loads for this domain. Generated mirror of .claude/systems/{dom}.yaml."
metadata:
  node_type: system
  type: reference
  domain: {dom}
  autonomy: {m.get('autonomy','full_ship')}
---

# {m['title']} — System Pack

{BANNER}

{desc}

- **Autonomy:** `{m.get('autonomy','full_ship')}`  |  **Gates:** {codelist(m.get('gates', []))}
- **Manifest:** `.claude/systems/{dom}.yaml`  |  **Entrypoint:** `/goal`

## Skills
- **Primary:** {codelist(primary)}
- **Support:** {codelist(support)}

## Mechanical agents
{codelist(m.get('agents', []))}

## Brand rules (hard constraints)
{wikilist(m.get('brand_rules', []))}

## Memory anchors (context)
{wikilist(m.get('memory_anchors', []))}

## n8n workflows
{wf_table}

```dataview
TABLE WITHOUT ID file.link AS Workflow, status AS Status, wf_id AS ID
FROM ""
WHERE node_type = "n8n-workflow" AND system = "{sysname}"
SORT status ASC, file.name ASC
```

## Verification (/goal runs these before declaring done)
{chr(10).join('- ' + v for v in (m.get('verification', []) or [])) or '_none_'}

## Example goals
{chr(10).join('- ' + e for e in (m.get('entrypoints', []) or [])) or '_none_'}
"""
    write(os.path.join(VAULT, sysname + ".md"), body)

    # --- per-workflow stub pages ---
    for wslug, w, dom, sysname in wf_pages:
        base = registry.get("n8n_base_url", "https://n8n.srv948776.hstgr.cloud")
        d = detail.get(w["id"], {})
        trig = ", ".join(d.get("trigger") or []) or "_(enrich: cron / webhook / manual)_"
        integ = ", ".join(f"`{x}`" for x in (d.get("integrations") or [])) or "_(enrich)_"
        creds = "\n".join(f"- `{c}`" for c in (d.get("creds") or [])) or "_(none detected / enrich)_"
        nodes = d.get("node_count", "?")
        wbody = f"""---
name: {wslug}
description: "n8n workflow: {w['name']} ({dom}, status {w['status']}). Trigger/credentials/integrations auto-detected from live nodes; Purpose + Gotchas await enrichment."
metadata:
  node_type: n8n-workflow
  type: reference
  wf_id: {w['id']}
  domain: {dom}
  system: {sysname}
  active: {str(w.get('active', False)).lower()}
  status: {w['status']}
---

# {w['name']}

{BANNER.replace('the manifest', 'build-fleet.sh / enrich by hand')}

- **ID:** `{w['id']}`
- **Status:** {w['status']}  |  **Active:** {w.get('active', False)}  |  **Nodes:** {nodes}
- **Domain:** [[{sysname}|{registry['domains'][dom]['title']}]]
- **Trigger:** {trig}
- **Open:** {base}/workflow/{w['id']}

## Integrations
{integ}

## Credentials
{creds}

## Purpose
_(enrich from nodes)_

## Gotchas
_(enrich: known traps; see [[n8n_workflow_status]])_

Part of [[{sysname}]].
"""
        write(os.path.join(VAULT, wslug + ".md"), wbody)

# --- _Systems.md dashboard ---
by_domain = fleet.get("by_domain", {})
active_by = {}
for w in fleet["workflows"]:
    if w["status"] == "active":
        active_by[w["domain"]] = active_by.get(w["domain"], 0) + 1
fleet_rows = "\n".join(
    f"| {d} | {active_by.get(d,0)} | {by_domain.get(d,0)} |"
    for d in sorted(by_domain)
)
pilot_links = ", ".join(f"[[system_{slug(m['domain'])}]]" for m in authored) or "_none yet_"
stub_list = ", ".join(
    meta["title"] for k, meta in registry["domains"].items()
    if not os.path.exists(os.path.join(SYS, meta["manifest"]))
) or "_none_"

dash = f"""---
name: _Systems
description: "System Packs dashboard — the domains /goal routes to, with their skills, workflows, and autonomy. Generated by scripts/systems/sync-vault.sh."
metadata:
  node_type: dashboard
  type: reference
---

# Systems

{BANNER}

Each **System Pack** is what `/goal` loads for a work domain: the skills, n8n workflows, brand rules, memory context, and mechanical agents needed to run that domain autonomously. Canonical source: `.claude/systems/`.

## Domains
```dataview
TABLE WITHOUT ID file.link AS System, domain AS Domain, autonomy AS Autonomy
FROM ""
WHERE node_type = "system"
SORT domain ASC
```

## n8n fleet by domain (snapshot {fleet.get('generated','')})
Total workflows: **{fleet.get('count','?')}**  |  active: **{fleet.get('active_count','?')}**

| Domain | Active | Total |
|---|---|---|
{fleet_rows}

## Workflow pages
```dataview
TABLE WITHOUT ID file.link AS Workflow, status AS Status, system AS System
FROM ""
WHERE node_type = "n8n-workflow"
SORT system ASC, status ASC
```

## Registry status
- **Pilot (authored):** {pilot_links}
- **Stub (awaiting manifest):** {stub_list}

See also: [[MEMORY]] · [[_Dashboard]] · [[n8n_workflow_status]]
"""
write(os.path.join(VAULT, "_Systems.md"), dash)

print(f"Wrote {len(written)} vault files:")
for n in sorted(written):
    print("  " + n)
PYEOF
